### ISSUE TITLE
Django issue 

### ISSUE THREAD

**Issue by meren** [meren/oligotyping#22]
Here is a problem observed on Mac OS 10.10.5:

```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.

  "unable to load templates.", RemovedInDjango110Warning)
```

**Comment by gkmngrgn** [comment]
@meren hello, which django version do you use?

I couldn't see any version number in this file:
https://github.com/meren/oligotyping/blob/master/requirements.txt

**Comment by meren** [comment]
Hi Gokmen!

I think what happened is that the user installed just recently, and ended up getting the very last version of Django which caused this incompatibility issue.

I copy-pasted from this report:

https://groups.google.com/d/msg/oligotyping/bVvdEVxvemI/ofji7lrFAgAJ


Best,

**Comment by joaosabino** [comment]
Hello,

When running:
oligotype mock.fa mock.fa-ENTROPY -c 1 -M 50 --gen-html

I have the problem:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.

  "unable to load templates.", RemovedInDjango110Warning)

I updated django and this is my current environment.

$ pip list
biopython (1.66)
cycler (0.9.0)
Django (1.9.1)
matplotlib (1.5.0)
numpy (1.10.2)
oligotyping (2.0)
pip (7.1.2)
pyparsing (2.0.7)
python-dateutil (2.4.2)
pytz (2015.7)
scipy (0.16.1)
setuptools (19.2)
six (1.10.0)

I still have the same problem with the latest version.

Mac OS El Capitan v 10.11.2

Best regards,
João

**Comment by meren** [comment]
Thank you very much, João.

The problem is that Django doesn't like our setup anymore, and complains that it will be incompatible with the next version. So we are fine until the next version :) I created this other report to address it (because that codebase is much more cleaner, and things are easier to test there) and I will simply carry that solution over to this one later on:

https://github.com/meren/anvio/issues/283

cc @gkmngrgn :)

**Comment by gkmngrgn** [comment]
@meren Sorry for delay, I'm still busy but I think to look at this issue (and anvio#283) this night. But I have some questions:

1. Why should not we specify version numbers for the dependencies, like Django>=1.4,<=1.8? Because 1.4 and 1.8 are LTS versions, but 1.9 is not. If this project and anvio are individual projects 
2. Do we have installable package for the project? Or everbody should install manually? Why?

By the way, I use Windows =) and One-click install can be benefical, am I wrong?

**Comment by meren** [comment]
Hi @gkmngrgn!

Thank you very much for looking into this. 

I try not to specify version numbers if it is not absolutely necessary, because usually the users end up having to install other open source scientific software pipelines that require later versions.

For this project unfortunately we don't have one (except the virtualbox solution http://merenlab.org/2014/09/02/virtualbox/), but for anvi'o I was much more careful, which has an OSX installer, as well as a docker image:

http://merenlab.org/2015/05/01/installation/

:)

I am hoping to put the oligotyping pipeline in docker hub as well.
